a2lix_translation_form:
  locale_provider: default
  locales: '%locale_list%'
  default_locale: '%locale%'
  required_locales: ['%locale%']
  templating: "@A2lixTranslationForm/bootstrap_3_layout.html.twig"