lexik_translation:
  fallback_locale: [en]         # (required) default locale(s) to use
  managed_locales: [fr, en] # (required) locales that the bundle has to manage
  base_layout: "LexikTranslationBundle::layout.html.twig"
  grid_input_type: text       # text|textarea
  grid_toggle_similar: false
  auto_cache_clean: false
  auto_cache_clean_interval: 600
  resources_registration:
    type: all  # all | files | database
    managed_locales_only: true