sonata_media:
  class:
    media: App\Entity\SonataMediaBundle\Media
    gallery: App\Entity\SonataMediaBundle\Gallery
    gallery_has_media: App\Entity\SonataMediaBundle\GalleryHasMedia
  db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
  default_context: default # you need to set a context
  contexts:
    default:  # the default context is mandatory
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file
      formats:
        small: { width: 100 , quality: 70}
        big: { width: 500 , quality: 70}
        share: { width: 1200, height: 627 , resizer: sonata.media.resizer.simple, quality: 70}
  cdn:
    server:
      path: /uploads/media # http://media.sonata-project.org/
  filesystem:
    local:
      directory: '%kernel.root_dir%/../public/uploads/media'
      create: false